{% set version = "2.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotroc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plotROC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plotROC/plotROC_{{ version }}.tar.gz
  sha256: 2f2c7ebec7b9cb8ad41b5ade1951b9d9f0ec12611ec369e12b10a34e5bb05b96

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-gridsvg
    - r-plyr
    - r-rlang
    - r-shiny
  run:
    - r-base
    - r-ggplot2
    - r-gridsvg
    - r-plyr
    - r-rlang
    - r-shiny

test:
  commands:
    - $R -e "library('plotROC')"           # [not win]
    - "\"%R%\" -e \"library('plotROC')\""  # [win]

about:
  home: http://sachsmc.github.io/plotROC
  license: MIT
  summary: Most ROC curve plots obscure the cutoff values and inhibit interpretation and comparison of multiple curves. This attempts to address those shortcomings by providing plotting and interactive tools. Functions are provided to generate an interactive ROC curve plot for web use, and print versions. A Shiny application
    implementing the functions is also included.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: plotROC
# Type: Package
# Title: Generate Useful ROC Curve Charts for Print and Interactive Use
# Version: 2.2.1
# Date: 2018-06-01
# Authors@R: c(person("Michael C.", "Sachs", role = c("aut", "cre"), email = "sachsmc@gmail.com"), person("Robert W.", "Corty", role = "ctb", email = "rcorty@gmail.com"))
# Maintainer: Michael C. Sachs <sachsmc@gmail.com>
# Description: Most ROC curve plots obscure the cutoff values and inhibit interpretation and comparison of multiple curves. This attempts to address those shortcomings by providing plotting and interactive tools. Functions are provided to generate an interactive ROC curve plot for web use, and print versions. A Shiny application implementing the functions is also included.
# License: MIT + file LICENSE
# URL: http://sachsmc.github.io/plotROC
# BugReports: http://github.com/sachsmc/plotROC/issues
# Depends: R (>= 3.0.0), ggplot2
# Imports: methods, grid, gridSVG, shiny, plyr, rlang
# Suggests: knitr, testthat, stringr, survivalROC, rmarkdown
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-23 07:28:03 UTC; sachsmc
# Author: Michael C. Sachs [aut, cre], Robert W. Corty [ctb]
# Repository: CRAN
# Date/Publication: 2018-06-23 07:52:56 UTC
