{% set version = "2.2.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotroc
  version: {{ version|replace("-", "_") }}

source:
  fn: plotROC_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/plotROC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/plotROC/plotROC_{{ version }}.tar.gz
  sha256: ef3fd972d0f600bb0c61df46b20e946ba317832a3ebc3827f9ec0374a990682e

build:
  noarch: generic
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2
    - r-gridsvg
    - r-plyr
    - r-shiny

  run:
    - r-base
    - r-ggplot2
    - r-gridsvg
    - r-plyr
    - r-shiny

test:
  commands:
    - $R -e "library('plotROC')"  # [not win]
    - "\"%R%\" -e \"library('plotROC')\""  # [win]

about:
  home: http://sachsmc.github.io/plotROC
  license: MIT
  summary: Most ROC curve plots obscure the cutoff values and inhibit interpretation and comparison
    of multiple curves. This attempts to address those shortcomings by providing plotting
    and interactive tools. Functions are provided to generate an interactive ROC curve
    plot for web use, and print versions. A Shiny application implementing the functions
    is also included.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
