# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RGgs+M9MRjT3kHtbumUVyjo/tq2QjqfCxzlfZO76RJoGd+IkPubnSJxiN7qjKaFOjUEk9vPgkaIGAsqf4fmrmyXQdFWvcxj49HzLLEutbsb+Rk7gFkQfbsNdRr2Ywh2eqibc5PYWmsb44F4aveUIlIBMO8dDWd9SPORJZJUtXmmkG1ZFgVdMzL3UERu7hWjRaFNzQcS/hMEc+WzaygC+Zj0A/9OFuP+qX1QUviYIvUczFw4/XUPFFtHMsqzYrUGXvtTZ5dXbJnv/9fI9FDhFVaJnZSHAY/1MJFu0zY5eodZZNTy+anj7/o2zOo2TLg2TpuaSfVtqSUU1RUseh/EregzB4bYoaz8N6MTPSOYHt9CcXTYIW0kr2i/+1/vdxDKYmfEjVCZKDg/HtvMxOJOdVVCPBtJs6ri/LBAmvF+FB+NEFDp4x8W5zxazdwUq9MuueVO4yJpEMU+D6EfwB2IoYbdyIrRVWK/JEBW7SBRKp7fMMp9MYPMSAxszDa3wtzBr6UfyP25iUzoIFuBEr+9sOepgk2NKqV+FaNiXNpro9xbnRuneZycQkJH788iOIUF+o8oSe78dsK8tFHrdQ45PglIPWi0p4qD7Tuc8GdkI6nWCd5VpDdl4J5q1+jkAUm+sk9ecrl5vRziuvI6OTKf/qXoDnonUeP3IHB8Vveqgfbc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
