travis:
  secure:
    BINSTAR_TOKEN: RGgs+M9MRjT3kHtbumUVyjo/tq2QjqfCxzlfZO76RJoGd+IkPubnSJxiN7qjKaFOjUEk9vPgkaIGAsqf4fmrmyXQdFWvcxj49HzLLEutbsb+Rk7gFkQfbsNdRr2Ywh2eqibc5PYWmsb44F4aveUIlIBMO8dDWd9SPORJZJUtXmmkG1ZFgVdMzL3UERu7hWjRaFNzQcS/hMEc+WzaygC+Zj0A/9OFuP+qX1QUviYIvUczFw4/XUPFFtHMsqzYrUGXvtTZ5dXbJnv/9fI9FDhFVaJnZSHAY/1MJFu0zY5eodZZNTy+anj7/o2zOo2TLg2TpuaSfVtqSUU1RUseh/EregzB4bYoaz8N6MTPSOYHt9CcXTYIW0kr2i/+1/vdxDKYmfEjVCZKDg/HtvMxOJOdVVCPBtJs6ri/LBAmvF+FB+NEFDp4x8W5zxazdwUq9MuueVO4yJpEMU+D6EfwB2IoYbdyIrRVWK/JEBW7SBRKp7fMMp9MYPMSAxszDa3wtzBr6UfyP25iUzoIFuBEr+9sOepgk2NKqV+FaNiXNpro9xbnRuneZycQkJH788iOIUF+o8oSe78dsK8tFHrdQ45PglIPWi0p4qD7Tuc8GdkI6nWCd5VpDdl4J5q1+jkAUm+sk9ecrl5vRziuvI6OTKf/qXoDnonUeP3IHB8Vveqgfbc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
