travis:
  secure:
    BINSTAR_TOKEN: c8pymdj+jwAlcp+wVEzl9l0yG6RUwYVDK/SnAlfQLmoLz5Ea1wdWu2hXwHFzkZwJUcVSg5hyRJEDi29oO9unOE4q8V29I8eyULXbcTlcODilBGAKiCAe88R3JkwyQgDgH8PzHGt9cyH8wleX8X6JnU1qgTs7A3W+l6VVPxTvPd4MN7OW88DaxWrsIwmwPDXjWZB8fobNWO7naBQgly2eK0CHc4rQOQ+iUBsY8eH+peNgcVc1HkdvUFWcpel3yCpXT8taF+PZWbm+kre2VWP2DPQIwI5EqUZLJuS9GjAMSroWSUFcUiDPDh7KJswVcAzv/1zbVPMKSCDJwiZk63h9NOjbXTcIqYn0LSVqXoevUQRjLPrs/3cyUBfgrAK+DKCL66fi20XKyr7ZHsCxWPa3Lmi7UEsOO/Q/0826kw4EiJq/Gzz3fvGKeucg53ZN/71H1+HOq11t5F7GQ0JdKB6EcR38UtttWFcLqU8NFHiKiCatTIhIYCCFjrbrVBV3B9beWFqC2alqBooUgPL37v2iQytHGCo8E6Bk62kLkANSb8XiCxhdh4+8zwU2o28PQvFpXjgNbvh7T7/7s337apb6MXMD2g9pkcSpwYc0EJVtWB/d1IqVAOl4SJNwKkFHarIkATV6y7VdAQJ21NmFi6GRMdCLMlGKL9kQ+RrXlRs4BfM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
