travis:
  secure:
    BINSTAR_TOKEN: FzValZ2DZJ5xCBxTWlJP+2qqI0X8u1gclrdT45viKym//59OfCq8Gk/2+BeF/1qb7BUJfN/GVmMXHO7PgVxNTSkE/48+hZi/bmBtowRxvsqDO/0Q2suEmLV5Pxf6Zd2dtL+lxotjZYgqCev96fYtY+zyFASjOyc3s4byXtTrWawQAsR87RglRvXMCtTYN7c1VvjrsD3kMDI53itTumdvi8lcnMR3A5NR/ntvZsGwVlTFyn+SYEv0Q81Q1jkN82MSF9I9BsLLKrCskhMoWc3Q6/RZt7TRvP10yvRDI1iummRXGdxoisbNdvW3K5qoTFZAQGOdz4l+Jko/pvIYUFnDwI2jxMq0l9slaIb1wKXYFwx/oM4WKTgsZJzUiuAJNOmgqiMkkrGkGZot2F08jpsgni4hNOTBYHwjGBv6YmAx8dEFwPmhsvh4eIXoeal7BXeBFDrPpfSHpTu/lOlhM/6ZHQOa+ssoc4THE/qzBmTYdWkNe1XKDeD99qUc8AiFnrmth//kK+Eto5/kFIQNDci8MTIvrtzW0fRcdkU6T3If7JPVO2eZ74lE4nYrOW38PGNr4TGVsEgvvIIRCWRr+bDEYXN6Wfe+baWz39GBZvCJmmtI9DryjUBwPed53l7rg+O6IJyoCQlT3cQ7+6WzbBCHjEg7XMm3Sfji9pxyIzJfaNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
