travis:
  secure:
    BINSTAR_TOKEN: MocQGVy47C0LbmSj/VTJT551lEfPukUww8sIvx/BRJwdhY7OQqsxs+SAnR7xGCwqcXGFUHXqvgo7nYbZlFcEgZxPwpEOXcDhF/GqkeTpqbgW1l8h0qV/UJ+TA4s2DBDbA2jHY/FKB+CoGck0JWta2PKz8eVPnd+Hw7QGHMjsGFPv7vas00TeV4ZcFgszGSMKsPyfHbE8/+3oZVUJ8B0TtD0v/qFrAEua3Xy05ZYUel4py2bTRONHCa65/v5ATEDR2pVtSvwSdvDcgtpUcbwSmjk31IStOBfUr4igcz+ZlfbkPw+Y8BJcZdTuSBlSdhi0rIPC+ThL6ZlYT8CpFgMFVU8+qENk5xxtgZ39A50jT9FdIRH/lGkgVN/RVaYGQScOyiRjubRSSUIYIOcwyb+ZP81hEtWK8iEy9pnVuY4bYZWI4sR9FFxJQwye+TiJuYcYKcpLjevH5IIpvhcejkJxDBYm/pyAs6PV3tfo7oI6ZlmwhhygjrmJftrtB8H5ZMIgz+sWRotwNjFuLHpDNNdZsgcHt37OmoRfbdFYnjrCmnJD32lA3mk5vt1aM61BbG3bg9YvfdctGbZrCVcJEBJR+UmiKoNG8OaXKPXu9ONjS7ekrR/zUL5ncPoVy4eAJKPUzA8tIjwfFZeAYWG1W85QmiLysFkpUrwN7a9GmCBDZcg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
